# Generated by Django 3.1.2 on 2020-12-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PeliSeries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=15)),
                ('fecha_public', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('img_noticia', models.ImageField(blank=True, null=True, upload_to='images/noticias', verbose_name='imagen')),
            ],
        ),
    ]
